### PR TITLE
Allow Laravel 4.2.* frameworks

### PR DESCRIPTION
**Pull request by tonglil**
Since no feature breaking changes were introduced to this library, it should still be allowed to work with Laravel 4.2.*.

### CODE REVIEW

**Comment by franzliedke** [comment]
Either that, or you can use the 0.9 branch.
Let me sleep over it. =)

**Comment by tonglil** [comment]
No problem! I see other [projects](https://github.com/AuraEQ/laravel-multi-tenant) do this so that it you can keep adding features/fixes without having to back-patch the code changes manually UNTIL the feature/fix requires the new version.

**Comment by franzliedke** [comment]
I'd prefer if you used the 0.9 branch of this library when working with Laravel 4.2. I'll be sure to backport any fixes, though. =)

**Comment by tonglil** [comment]
No problem, cheers!

**Pull request closed without merging**
